from django.db import models
from django.utils.timezone import now
from db.vsolvmodels import VsolvModels
class Entry(VsolvModels):
    branch_id = models.IntegerField(null=False, blank=False, default=0)
    fiscalyear = models.IntegerField(null=False, blank=False, default=0)
    period = models.IntegerField(null=False, blank=False, default=0)
    module = models.IntegerField(default=0)
    screen = models.IntegerField(default=0)
    transactiondate = models.DateField(null=False, blank=False)
    transactiontime = models.TimeField(null=False, blank=False)
    valuedate = models.DateField(null=False, blank=False)
    valuetime = models.TimeField(null=False, blank=False)
    cbsdate = models.DateTimeField(null=False, blank=False)
    localcurrency = models.IntegerField(null=False, blank=False, default=0)
    localexchangerate = models.IntegerField(null=False, blank=False, default=0)
    currency = models.IntegerField(null=False, blank=False, default=0)
    exchangerate = models.IntegerField(null=False, blank=False, default=0)
    isprevyrentry = models.IntegerField(null=False, blank=False, default=0)
    reversalentry = models.IntegerField(null=False, blank=False, default=0)
    refno = models.CharField(max_length=30, null=False, blank=False, default=0)
    crno = models.CharField(max_length=30, null=False, blank=False, default=0)
    refid = models.IntegerField(null=False, blank=False, default=0)
    reftableid = models.IntegerField(null=False, blank=False, default=0)
    type = models.IntegerField(null=False, blank=False, default=0)
    gl = models.BigIntegerField(null=False, blank=False, default=0)
    apcatno = models.IntegerField(null=False, blank=False, default=0)
    apsubcatno = models.IntegerField(null=False, blank=False, default=0)
    wisefinmap = models.IntegerField(null=False, blank=False, default=0)
    glremarks = models.CharField(max_length=250, null=False, blank=False, default=0)
    amount = models.DecimalField(max_digits=16, decimal_places=2)
    fcamount = models.DecimalField(max_digits=16, decimal_places=2,default=0)
    ackrefno = models.CharField(max_length=128, null=True, blank=True, default=0)
    entry_status = models.SmallIntegerField(default=0)
    is_error = models.SmallIntegerField(default=0)
    errordescription = models.TextField(default=0)
    glnodescription = models.TextField(default=0)
    group_id = models.BigIntegerField(null=True)
    entry_process_id = models.SmallIntegerField(default=0)
    bulk_status = models.SmallIntegerField(default=0)
    bulk_is_error = models.SmallIntegerField(default=0)
    bulk_errordescription = models.TextField(default=0)
    segment_1=models.CharField(max_length=64,null=True)
    segment_2=models.CharField(max_length=64,null=True)
    segment_3=models.CharField(max_length=64,null=True)
    segment_4=models.CharField(max_length=64,null=True)
    segment_5=models.IntegerField(null=True)
    segment_6=models.IntegerField(null=True)
    segment_7=models.IntegerField(null=True)
    segment_8=models.IntegerField(null=True)
    segment_9=models.IntegerField(null=True)
    segment_10=models.IntegerField(null=True)
    reference_10=models.CharField(max_length=240,null=True)
    status = models.SmallIntegerField(default=1)
    created_by = models.IntegerField(null=False, blank=False)
    created_date = models.DateTimeField(default=now)
    updated_by = models.IntegerField(null=True, blank=True)
    updated_date = models.DateTimeField(null=True, blank=True)

class ParameterTables(VsolvModels):
    name = models.CharField(max_length=64, null=False, blank=False)
    is_parent=models.IntegerField(default=0)
    displayname=models.CharField(max_length=64,null=True, blank=True)
    status = models.SmallIntegerField(default=1)
    created_by = models.IntegerField(null=False, blank=False)
    created_date = models.DateTimeField(default=now)
    updated_by = models.IntegerField(null=True, blank=True)
    updated_date = models.DateTimeField(null=True, blank=True)

class ParameterName(VsolvModels):
    code = models.CharField(max_length=32, null=False, blank=False)
    paramname = models.CharField(max_length=64, null=False, blank=False)
    columnname = models.TextField(null=False)
    columnnamecredit = models.TextField(default=0)
    columnnamedebit = models.TextField(default=0)
    status = models.SmallIntegerField(default=1)
    created_by = models.IntegerField(null=False, blank=False)
    created_date = models.DateTimeField(default=now)
    updated_by = models.IntegerField(null=True, blank=True)
    updated_date = models.DateTimeField(null=True, blank=True)

class EntryTemplate(VsolvModels):
    parametername_id=models.IntegerField(null=False, blank=False)
    gl_no=models.CharField(max_length=32, null=True, blank=True)
    transaction=models.CharField(max_length=32, null=True, blank=True)
    Values = models.DecimalField(max_digits=16, decimal_places=2, null=True, blank=True)
    value_to_taken=models.CharField(max_length=64, null=True, blank=True)
    wisefin_category=models.CharField(max_length=32, null=True, blank=True)
    wisefin_subcategory=models.CharField(max_length=64, null=True, blank=True)
    display=models.CharField(max_length=32, null=True, blank=True)
    status = models.SmallIntegerField(default=1)
    created_by = models.IntegerField(null=False, blank=False)
    created_date = models.DateTimeField(default=now)
    updated_by = models.IntegerField(null=True, blank=True)
    updated_date = models.DateTimeField(null=True, blank=True)

class Oraclesegment(VsolvModels):
    vendortype=models.CharField(max_length=32, null=True, blank=True)
    segmentno=models.CharField(max_length=64, null=True, blank=True)
    values = models.IntegerField(null=True, blank=True)
    status = models.SmallIntegerField(default=1)
    created_by = models.IntegerField(null=False, blank=False)
    created_date = models.DateTimeField(default=now)
    updated_by = models.IntegerField(null=True, blank=True)
    updated_date = models.DateTimeField(null=True, blank=True)

class ModuleEOD(VsolvModels):
    date = models.DateTimeField(null=True, blank=True)
    eodflag = models.SmallIntegerField(default=0)
    status = models.SmallIntegerField(default=1)
    created_by = models.IntegerField(null=False, blank=False)
    created_date = models.DateTimeField(default=now)
    updated_by = models.IntegerField(null=True, blank=True)
    updated_date = models.DateTimeField(null=True, blank=True)