from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from ecfservice.controller import ecfcontroller, ecfcocontroller

urlpatterns = [
    path('create_ecf', ecfcontroller.create_ecf, name='create_ecf'),
    path('ecfhdr/<ecf_id>', ecfcontroller.fetchone_ecfhdr, name='ecfhdr'),
    path('ecf_covernote/<ecf_id>', ecfcontroller.get_ecf_covernote, name='ecf_covernote'),
    path('ecf_covernoteadv/<ecf_id>', ecfcontroller.get_ecfadv_covernote, name='ecf_covernoteadv'),
    path('get_ecftype', ecfcontroller.get_ecftype, name='get_ecftype'),
    path('get_ppx', ecfcontroller.get_ppx, name='get_ppx'),
    path('get_status', ecfcontroller.get_status, name='get_status'),
    path('get_status_ddl', ecfcontroller.get_status_ddl, name='get_status_ddl'),
    path('get_payto/<typeid>', ecfcontroller.get_payto, name='get_payto'),
    path('ecf_submit', ecfcontroller.ecf_submit, name='ecf_submit'),
    path('ecf_hdrsearch', ecfcontroller.search_ecfheader, name='ecf_hdrsearch'),
    path('create_invoiveheader', ecfcontroller.create_invhdr, name='create_invoiveheader'),
    path('create_invoivepo', ecfcontroller.create_invpo, name='create_invoivepo'),
    path('create_invoivedtl', ecfcontroller.create_invoivedtl, name='create_invoivedtl'),
    path('po_list', ecfcontroller.po_list, name='po_list'),
    path('pono_details', ecfcontroller.get_ponodtl, name='pono_details'),
    path('create_debit', ecfcontroller.create_debit, name='create_debit'),
    path('create_credit', ecfcontroller.create_credit, name='create_credit'),
    # path('update_invpo', ecfcontroller.update_invpo, name='update_invpo'),
    path('ecfapprove', ecfcontroller.ecfapprove, name='ecfapprove'),
    path('ecfnextapprove', ecfcontroller.ecfnextapprove, name='ecfnextapprove'),
    path('ecfreject', ecfcontroller.ecfreject, name='ecfreject'),
    path('ecf_approvallist', ecfcontroller.fetch_ecfapproval_list, name='ecf_approvallist'),
    path('ecf_approvalsearch', ecfcontroller.search_ecfapprovalheader, name='ecf_approvalsearch'),
    path('get_tax', ecfcontroller.get_tax, name='get_tax'),
    path('create_invoivedetail', ecfcontroller.create_invoivedetail, name='create_invoivedetail'),
    path('ecfpayment_list/<supplier_id>/<paymode_id>', ecfcontroller.ecfpayment_list, name='ecfpayment_list'),
    path('invhdr/<inv_id>', ecfcontroller.fetchone_invhdr, name='fetchone_invhdr'),
    path('get_suppliertype', ecfcontroller.get_suppliertype, name='get_suppliertype'),
    path('invdtl/<invdtl_id>', ecfcontroller.fetchone_invdtl, name='fetchone_invdtl'),
    path('ecfdelete/<ecf_id>', ecfcontroller.delete_ecfhdr, name='delete_ecfhdr'),
    path('invdelete/<invhdr_id>', ecfcontroller.delete_invhdr, name='delete_invhdr'),
    path('invdtldelete/<invdtl_id>', ecfcontroller.delete_invdtl, name='delete_invdtl'),
    path('debitdelete/<dbt_id>', ecfcontroller.delete_debit, name='delete_debit'),
    path('creditdelete/<cdt_id>', ecfcontroller.delete_credit, name='delete_credit'),
    path('create_ecfmod', ecfcontroller.create_ecfmod, name='create_ecfmod'),
    path('create_invoiveheadermod', ecfcontroller.create_invhdrmod, name='create_invoiveheadermod'),
    path('create_invoivepomod', ecfcontroller.create_invpomod, name='create_invoivepomod'),
    path('create_invoivedtlmod', ecfcontroller.create_invoivedtlmod, name='create_invoivedtlmod'),
    path('create_invoivedetailmod', ecfcontroller.create_invoivedetailmod, name='create_invoivedetailmod'),
    path('create_debitmod', ecfcontroller.create_debitmod, name='create_debitmod'),
    path('create_creditmod', ecfcontroller.create_creditmod, name='create_creditmod'),
    path('tds/<supplier_id>',ecfcontroller.fetch_suptds,name='fetch_suptds'),
    path('tdstaxrate',ecfcontroller.fetch_tdstaxrate,name='fetch_tdstaxrate'),
    path('tdscal/<creditamount>/<tdsamt>',ecfcontroller.fetch_ratecal,name='fetch_ratecal'),
    path('get_tds', ecfcontroller.get_tds, name='get_tds'),
    path('ecfheader', ecfcontroller.create_ecfheader, name='overall create'),
    path('get_ecf/<ecf_id>', ecfcontroller.fetch_ecf, name='overall get'),
    path('get_ecfno/<ecf_no>', ecfcontroller.fetch_ecfno, name='fetch_ecfno'),
    path('ecfpaymode_list/<paymode_id>', ecfcontroller.ecfpaymode, name='ecfpaymode_list'),
    path('get_advancetype', ecfcontroller.get_advancetype, name='get_advancetype'),
    path('dd', ecfcontroller.employe_role_get, name='get_advancetype'),
    path('ecffile/<file_id>', ecfcontroller.fetch_file, name='download'),
    path('deletefile/<file_id>', ecfcontroller.delete_file, name='deletefile'),
    #ecfcosummary#test
    path('ecfco', ecfcocontroller.ecfco_list, name='get_ecfcosummary'),
    path('ecfcodownload', ecfcocontroller.ecfco_download, name='get_ecfcosummary'),
    path('get_trans/<No>',ecfcocontroller.get_ecftransget,name='ecftransaction'),
    path('getecf/<No>', ecfcocontroller.get_ecf, name='ecftransaction'),
    path('searchempquery', ecfcocontroller.search_empquery, name='searchloanappno'),
    path('get_ecfstatus', ecfcocontroller.fetch_ecfstatus_list, name='dropdown'),
    path('get_ecfnoo/<ecf_no>', ecfcontroller.fetch_ecfnoo, name='fetch_ecfno'),
    path('get_ecftype_single/<ecftype_id>', ecfcontroller.get_ecftypesingle, name='get_ecftypesingle'),
    path('get_status_ddl', ecfcontroller.get_status_ddl, name='get_status_ddl'),
    path('gsttypee/<No>/<branch_id>', ecfcontroller.ds, name='suppliergsttype'),
    # path('schedulereport_download', ecfcocontroller.schedule_report_download,name='download_excel'),
    #ecf_common_summary
    path('fetch_ecf_common_summary', ecfcontroller.fetch_ecf_common_summary, name='fetch_ecf_common_summary'),
    path('apupdate', ecfcontroller.create_apstatus, name='apstatusupateinecf'),
    path('fileview/<file_id>', ecfcontroller.view_file, name='view_file'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)